spring.application.name=sismo

# ===============================
# Configuración del servidor
# ===============================
server.port=8080

# ===============================
# Configuración de la base de datos (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/mitosis_db
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# Logging
# ===============================
logging.level.org.springframework=INFO
logging.level.com.mitosis.api=DEBUG

# ===============================
# Seguridad (JWT)
# ===============================
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000   # 1 hora en milisegundos

# ===============================
# OpenAPI / Swagger
# ===============================

# Título y descripción de la API
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# Personalización de la documentación
springdoc.api-docs.path=/v3/api-docs
springdoc.packages-to-scan=com.mito.sismo.controller
springdoc.version=1.0.0
